# Generated by Django 4.1.5 on 2024-04-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0004_groupbrandaccess"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroupBrandAccess",
        ),
    ]
