# Generated by Django 4.1.5 on 2024-04-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0006_branduserlink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BrandUserLink",
        ),
    ]
