# Generated by Django 4.1.5 on 2024-04-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0008_branduserlink"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branduserlink",
            options={
                "verbose_name": "Brands Access Permissions",
                "verbose_name_plural": "Brands Access Permissions",
            },
        ),
        migrations.RemoveField(
            model_name="branduserlink",
            name="local_brand",
        ),
        migrations.AddField(
            model_name="branduserlink",
            name="local_brands",
            field=models.ManyToManyField(to="brands.localbrand"),
        ),
    ]
