# Generated by Django 4.1.5 on 2024-04-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0009_alter_branduserlink_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_id",
                    models.AutoField(
                        db_column="category_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
