# Generated by Django 4.1.5 on 2024-04-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0010_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_id",
            new_name="id",
        ),
    ]
