# Generated by Django 4.1.5 on 2024-04-22 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0017_alter_campaignadditionaldetails_category"),
        ("brands", "0012_rename_id_category_category_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
