# Generated by Django 4.1.5 on 2024-04-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0014_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BrandUserLink",
        ),
    ]
