# Generated by Django 4.1.5 on 2024-04-29 06:25

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("products", "0029_delete_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brands", "0016_branduserlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="AccessTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allowed_markets", models.ManyToManyField(to="products.market")),
                ("category", models.ManyToManyField(to="brands.category")),
                ("local_brands", models.ManyToManyField(to="brands.localbrand")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permissions",
                "verbose_name_plural": "Access Permissions",
            },
        ),
    ]
