# Generated by Django 4.1.5 on 2024-05-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RoleAccess", "0002_customusergroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesstable",
            options={
                "verbose_name": "User Permissions",
                "verbose_name_plural": "Access Restrictions",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
    ]
