# Generated by Django 4.1.5 on 2024-05-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0018_delete_userprofile"),
        ("products", "0029_delete_country"),
        ("RoleAccess", "0003_alter_accesstable_options_alter_role_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesstable",
            name="allowed_markets",
        ),
        migrations.RemoveField(
            model_name="accesstable",
            name="local_brands",
        ),
        migrations.AddField(
            model_name="accesstable",
            name="brands",
            field=models.ManyToManyField(blank=True, to="brands.brand"),
        ),
        migrations.AddField(
            model_name="accesstable",
            name="markets",
            field=models.ManyToManyField(blank=True, to="products.market"),
        ),
        migrations.AlterField(
            model_name="accesstable",
            name="category",
            field=models.ManyToManyField(blank=True, to="brands.category"),
        ),
    ]
