# Generated by Django 4.1.5 on 2024-05-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0018_delete_userprofile"),
        ("RoleAccess", "0006_alter_accesstable_brands"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstable",
            name="brands",
            field=models.ManyToManyField(blank=True, to="brands.localbrand"),
        ),
    ]
