# Generated by Django 4.1.5 on 2024-05-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RoleAccess", "0007_alter_accesstable_brands"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesstable",
            old_name="brands",
            new_name="local_brands",
        ),
    ]
