# Generated by Django 4.1.5 on 2024-04-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
