# Generated by Django 4.1.5 on 2024-04-17 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0011_remove_campaignadditionaldetails_brand_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Cosmetics", "Cosmetics"),
                            ("Grocery", "Grocery"),
                            ("Snacks", "Snacks"),
                            ("Medicines", "Medicines"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Category User Link",
                "verbose_name_plural": "Category User Links",
            },
        ),
    ]
