# Generated by Django 4.1.5 on 2024-04-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0014_category"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
