# Generated by Django 4.1.5 on 2024-04-22 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0011_rename_category_id_category_id"),
        ("campaigns", "0015_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignadditionaldetails",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="brands.category"
            ),
        ),
    ]
