# Generated by Django 4.1.5 on 2024-04-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0016_alter_campaignadditionaldetails_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignadditionaldetails",
            name="category",
            field=models.CharField(
                choices=[
                    ("Cosmetics", "Cosmetics"),
                    ("Grocery", "Grocery"),
                    ("Snacks", "Snacks"),
                    ("Medicines", "Medicines"),
                ],
                max_length=100,
            ),
        ),
    ]
