# Generated by Django 4.1.5 on 2024-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0014_category"),
        ("campaigns", "0018_alter_campaignadditionaldetails_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryuserlink",
            name="category",
        ),
        migrations.AddField(
            model_name="categoryuserlink",
            name="category",
            field=models.ManyToManyField(to="brands.category"),
        ),
    ]
