# Generated by Django 4.1.5 on 2024-04-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0019_remove_categoryuserlink_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryuserlink",
            options={
                "verbose_name": "Category User Permissions",
                "verbose_name_plural": "Category Access Permissions",
            },
        ),
    ]
