# Generated by Django 4.1.5 on 2024-05-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0020_alter_categoryuserlink_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCampaign",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("campaign_name", models.CharField(max_length=500)),
                ("key_contact_first_name", models.CharField(max_length=500)),
                ("key_contact_last_name", models.CharField(max_length=500)),
                ("key_contact_email_address", models.EmailField(max_length=254)),
                (
                    "secondary_contact_first_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "secondary_contact_last_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "secondary_contact_email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("date_added", models.DateField(blank=True, editable=False)),
                ("date_updated", models.DateField(blank=True, editable=False)),
                ("updated_by", models.CharField(max_length=500, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical campaign",
                "verbose_name_plural": "historical campaigns",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
