# Generated by Django 4.1.5 on 2024-04-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0011_remove_campaignadditionaldetails_brand_code_and_more"),
        ("products", "0019_useraccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccess",
            name="allowed_categories",
            field=models.ManyToManyField(to="campaigns.campaignadditionaldetails"),
        ),
    ]
