# Generated by Django 4.1.5 on 2024-04-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_useraccess_allowed_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccess",
            name="allowed_categories",
        ),
    ]
