# Generated by Django 4.1.5 on 2024-04-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_remove_useraccess_allowed_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraccess",
            options={
                "verbose_name": "User Access Markets",
                "verbose_name_plural": "Market Access Permissions",
            },
        ),
    ]
