# Generated by Django 4.1.5 on 2024-04-22 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0022_alter_useraccess_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserAccess",
            new_name="UserMarketAccess",
        ),
    ]
