# Generated by Django 4.1.5 on 2024-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_rename_useraccess_usermarketaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2, unique=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
