# Generated by Django 4.1.5 on 2024-04-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("city", models.CharField(max_length=255)),
                ("city_ascii", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("country", models.CharField(max_length=255)),
                ("iso2", models.CharField(max_length=2)),
                ("iso3", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=255)),
                ("capital", models.CharField(blank=True, max_length=255, null=True)),
                ("population", models.IntegerField()),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name="country",
            name="country",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
