# Generated by Django 4.1.5 on 2024-04-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_city_alter_country_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
    ]
