# Generated by Django 4.1.5 on 2024-04-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0026_delete_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodePosition",
            fields=[
                (
                    "code",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
