# Generated by Django 4.1.5 on 2024-04-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_codeposition"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CodePosition",
        ),
    ]
