# Generated by Django 4.1.5 on 2024-04-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_delete_codeposition"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Country",
        ),
    ]
