# Generated by Django 4.1.5 on 2024-05-09 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_delete_country"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserMarketAccess",
        ),
    ]
